# Python Numpy

- NumPy is a python package / library that stands for 'Numerical Python'
- It is used for scientific computing by using array objects
- It uses array/vector and matrix operations which save coding time and execution time; no need for while loops in lists


1. Printing / Running cells
2. Importing / installing packages
3. NumPy Arrays
4. Creating Arrays
    - Manually
    - Set/standard Matrix Types
    - From a List
    - Appending an Existing Array
5. Array Indexing
6. Array DataTypes
7. Array Maths
8. Array Mathimatical Functions
9. Reshape
10. Transpose
11. Broadcasting

##  1. Printing / Running cells


In [1]:
# passing values

# CTRL + Enter = Run

a = 10
b = 11
c = "Hello"

In [2]:
# To Print
print(a)
print(b)
c

10
11


'Hello'

## 2. Importing / Installing packages  



In [3]:
# Packages / libraries

import os #provides functions for interacting with the operating system
import numpy as np

# pip install numpy - in the terminal

## 3. Arrays 

A numpy array is a grid of values. All have the same type

In [4]:
# Creating an array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
# checking the type of a
type(a)

numpy.ndarray

In [6]:
# checking the number of elements per dimension
a.shape

(4,)

In [7]:
# Selecting / indexing elements from the array
a[0]
a[-1]
a[3]

4

In [10]:
# Indexing elements that don't exist (out of bounds)
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [11]:
# Creating error check to avoid stoping the script
try:
    a[4]
except IndexError as e:
    print(e)
    


index 4 is out of bounds for axis 0 with size 4


In [12]:
# changing the elements of the array

a[0] = 300
a

array([300,   2,   3,   4])

In [13]:
# creating a 2 D array

a = np.array([[1,2,3], [1,2,3]])
a
#a.shape

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
# creating a 3x3 Matrix
a = np.array([[1,2,3], [1,2,3], [1,2,3]])
a
#a.shape

# To flatten the matrix 
b = np.hstack(a)

print(a)
b

[[1 2 3]
 [1 2 3]
 [1 2 3]]


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

## 4. Creating Arrays

### 4.1 Set matrix types

In [15]:
# 2x2 with zero values

np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
# NxN with 1 values

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# When we want to pass a specific number

np.full((4,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [18]:
# generate random numbers

a = np.random.random((5,5))*1000
a

array([[563.73223838, 290.33041166, 655.56347571, 362.03693019,
        151.90909541],
       [173.47457178, 389.04015947, 125.31979096, 251.40801783,
        780.22713035],
       [403.57573014,  16.66796666, 235.53443192, 371.19158626,
        791.92597085],
       [372.91207787, 986.35190891,  95.40264787, 905.04495441,
        793.31583139],
       [881.85449102, 351.09835981, 371.60977206, 270.08030965,
        871.7031503 ]])

### 4.2 From a List

In [19]:
a_list = [1,2,3,4]
a_list

[1, 2, 3, 4]

In [20]:
#a_list.shape
# b_list.shape # will give us an error

a = np.array(a_list)

#shape
a.shape
a

#specifying the type
a = np.array(a_list, dtype = float)
a

array([1., 2., 3., 4.])

### 4.3 Appending an Exisitng Array

In [21]:
# Appending an array

a = np.array([])

for i in range(100):
    a = np.append(a,i)

a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

## 5. Array indexing


In [22]:
a = np.random.random((3,5)) * 100
a = a.round()
a

array([[40.,  2., 95., 46., 87.],
       [ 5., 91., 84., 92.,  5.],
       [86., 59., 79., 64., 24.]])

In [23]:
a.shape

(3, 5)

In [24]:
# first value is the row, second is the column

In [25]:
a[2,0]

86.0

In [26]:
a[0,2]

95.0

In [27]:
a[0:2,]

array([[40.,  2., 95., 46., 87.],
       [ 5., 91., 84., 92.,  5.]])

In [28]:
a[2]

array([86., 59., 79., 64., 24.])

In [29]:
# last 2 numbers
a[2, 3:5]

array([64., 24.])

In [30]:
# first 2 numbers
a[0, 0:2]

array([40.,  2.])

In [31]:
# middle 2x2 matrix
a[1:3,2:4]

# middle 3x3 matrix
a[0:3, 0:3]

array([[40.,  2., 95.],
       [ 5., 91., 84.],
       [86., 59., 79.]])

## 6. Array datatypes

In [32]:
# Integer # Numpy choose the datatype

a = np.array([1,2,3])
a.dtype

dtype('int64')

In [33]:
# Float  # Numpy choose the datatype
a = np.array([1.,2.,3.])
a.dtype

dtype('float64')

In [34]:
# Specify a datatype
a = np.array([1,2,3], dtype = 'float')
a.dtype

dtype('float64')

## 7. Numpy Array Basic Maths

Mathematical functions operate elementwise on arrays

In [35]:
# creating the arrays
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

In [36]:
# SUM

a + b
np.add(a,b)

array([ 8, 10, 12, 14, 16, 18])

In [37]:
# Minus

a - b
np.subtract(a,b)

array([-6, -6, -6, -6, -6, -6])

In [38]:
# Multiply
a * b
np.multiply(a,b)

array([ 7, 16, 27, 40, 55, 72])

In [39]:
# Division

a/b
np.divide(a,b)

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [40]:
# Square root

np.sqrt(b)


array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162])

In [41]:
# Dot product and Matrix Maths
# Note: when we multiply in Numpy, we use elementwise multiplication, not matrix multiplication like MATLAP

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([2, 3])
d = np.array([4, 5])



In [42]:
# Inner product of vectors

c.dot(d)
np.dot(c,d)

# NumPy - elementwise multiplication
# (2*4) + (3*5)
# 8 + 15 = 23


23

In [43]:
# Matrix vector product

a.dot(c)
np.dot(a,c)

# NumPy Elementwise
# ((1*2) + (2*3)) , ((3*2) + (4*3))
# (2 + 6) , (6 + 12)
# 8, 18

array([ 8, 18])

In [44]:
a

array([[1, 2],
       [3, 4]])

In [45]:
b

array([[5, 6],
       [7, 8]])

In [46]:
# Matrix by matrix product


a.dot(b)
np.dot(a,b)

# NumPy Elementwise
# (1*5) + (2*7), (1*6) + (2*8)
# (3*5) + (4*7), (3*6) + (4*8)

# 5+14, 6+16
# 15+28, 18+32

# 19, 22
# 43, 50


array([[19, 22],
       [43, 50]])

## 8. Mathimatical Functions

In [47]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# Sum of all elements

np.sum(a)

21

In [49]:
# sums the values by column
np.sum(a, axis=0)

array([ 9, 12])

In [50]:
# sums the values by row
np.sum(a, axis=1)

array([ 3,  7, 11])

## 9. Reshaping

In [51]:
a.shape

(3, 2)

In [52]:
# reshaping
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# flattens
np.hstack(a)

array([1, 2, 3, 4, 5, 6])

In [54]:
#generate new array and reshape

a = np.arange(10).reshape((2,5))

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 10. Transpose - Turn the rows into columns and vice versa

In [55]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
# One way of Transp
a.T

# ANother way
np.transpose(a)


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## 11. Broadcasting

Allows numpy to work with arrays of different shapes when performing arithmetic operations

In [57]:
a = np.arange(15).reshape((5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
b = np.array([5,2,1])
b

array([5, 2, 1])

In [59]:
a * b

array([[ 0,  2,  2],
       [15,  8,  5],
       [30, 14,  8],
       [45, 20, 11],
       [60, 26, 14]])

In [60]:
a + b

array([[ 5,  3,  3],
       [ 8,  6,  6],
       [11,  9,  9],
       [14, 12, 12],
       [17, 15, 15]])

In [61]:
a/100*2

array([[0.  , 0.02, 0.04],
       [0.06, 0.08, 0.1 ],
       [0.12, 0.14, 0.16],
       [0.18, 0.2 , 0.22],
       [0.24, 0.26, 0.28]])